ReadSoustraction:
  db:
    vitis: '/media/data/db/ncbi/vitis/vitis'
    phiX:  '/media/data/db/ncbi/phiX/phiX174'
bin:
  bowtie: '/usr/local/bin/bowtie2'
  samtools: '/usr/bin/samtools'
  bedtools: '/usr/bin/bedtools'
  prinseq: '/usr/local/bin/prinseq-lite.pl'
servers:
  genotoul:
    adress: 'genotoul.toulouse.inra.fr'
    username: 'stheil'
    db:
      nr: '/bank/blastdb/nr'
      nt: '/bank/blastdb/nt'
      refseq_vir_nucl: '/save/stheil/db/refseq_vir/viral.genomic.fna'
      refseq_vir_prot: '/save/stheil/db/refseq_vir/viral.protein.faa'
      pfam: '/home/stheil/save/db/pfam/pfam_viruses_rpsdb'
      all_vir_nucl: '/home/stheil/save/db/all_vir/all_vir_nucl.fna'
      all_vir_prot: '/home/stheil/save/db/all_vir/all_vir_prot.faa'
    scratch: '/work/stheil'
    bin:
      blastx: 'blastx+'
      blastn: 'blastn+'
  avakas:
    adress: 'avakas.mcia.univ-bordeaux.fr'
    username: 'stheil'
    db:
      nr: '/home/stheil/db/nr/nr'
      nt: '/home/stheil/db/nt/nt'
      all_vir_nucl: '/home/stheil/scratch/db/all_vir/all_vir_nucl.fna'
      all_vir_prot: '/home/stheil/scratch/db/all_vir/all_vir_prot.faa'
      refseq_vir_nucl: '/home/stheil/scratch/db/refseq_vir/viral.genomic.fna'
      refseq_vir_prot: '/home/stheil/scratch/db/refseq_vir/viral.protein.faa'
      pfam: '/home/stheil/db/pfam/pfam_viruses_rpsdb'
    scratch: '/scratch/stheil'
    bin:
      blastx: 'blastx'
      blastn: 'blastn'
AutoMapper:
  db:
    nt: /media/data/db/ncbi/nt/nt
    refseq_vir_nucl: /media/data/db/ncbi/refseq_vir/viral.genomic.fna
    all_vir_nucl: /media/data/db/ncbi/all_vir/all_vir_nucl.fna
